name: "Terraform destroy"

on:
  workflow_dispatch: 

jobs:
  terraform:
    name: "Terraform destroy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar as credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: us-east-1
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
      - name: "Terraform init"
        working-directory: ./src ##para executar os comandos dentro da pasta src do projeto
        run:  terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}" ##aqui com o "run" (que não é uma action) será executado um comando
    
      - name: Terraform destroy
        working-directory: ./src
        run: terraform destroy --auto-approve